import type { Metadata } from 'next'
import './globals.css'
import { SidebarProvider } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='antialiased'>
        <SidebarProvider>
          <AppSidebar />
          <main className='flex flex-1 flex-col gap-4 p-4 pt-0 w-full h-screen'>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
